services:
  - type: web
    name: swft-doorbell
    runtime: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --chdir server app:app
    envVars:
      - key: SERVER_API_KEY
        generateValue: true
      - key: PORT
        value: 10000
    rootDir: .
